[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "DensityRatioScore"
version = "0.1.0"
description = "Utilities for computing density ratio scores."
readme = "README.md"
requires-python = ">=3.10"
authors = [
    { name = "Brad Shook" }
]
dependencies = [
    "numpy",
    "pandas",
    "scikit-learn",
]